<?php


$this->headScript()->prependFile($this->basePath('js/anuncio/anuncio/add.js'));

?>

<script async defer
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAbs17_TjO4QfDkKb8jVPcdZRctytHJ1aM&callback=initMap">
    </script>
    
<div class="row">
<div class="col-xs-12">
    
    <div id="map" style="height: 100%; width:100%"></div>
    
</div>
</div>

<div class="row">
    <div class="col-xs-12">


<?php


$title = 'Incluir Anúncio';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
//$form->setAttribute('action', $this->url('anuncio', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);



?>








    <div id='msg_erro_geral' class='alert alert-danger' role='alert'></div>
    <div id='msg_sucesso' class='alert alert-success' role='alert'></div>
    
    <form>
        
        <div class="form-group">
            <label>Código de Barras</label>
            <?php echo $this->formRow($form->get('cdBarra'));?>
          </div>
        <div class="form-group">
            <label>Nome</label>
            <?php echo $this->formRow($form->get('nmMat'));?>
        </div>
        <div class="form-group">
            <label>Marca</label>
            <?php echo $this->formRow($form->get('marca'));?>
        </div>
        <div class="form-group">
            <label>Unidade de Medida</label>
            <?php echo $this->formRow($form->get('tpUnMedida'));?>
        </div>
        <div class="form-group">
            <label>Quantidade Unidade Medida</label>
            <?php echo $this->formRow($form->get('qtUnMedida'));?>
        </div>
        <div class="form-group">
            <label>Preço</label>
            <?php echo $this->formRow($form->get('preco'));?>
        </div>
        <div class="form-group">
            <label>Latitude</label>
            <?php echo $this->formRow($form->get('latitude'));?>
        </div>
        <div class="form-group">
            <label>Longitude</label>
            <?php echo $this->formRow($form->get('longitude'));?>
        </div>
        
        
        <div id="add_imagem" class="form-group" style="display:none">
        
            <label for="sel_classe" class="col-xs-2 control-label">Imagem:</label>
            
            <div class="fileinput fileinput-new" data-provides="fileinput">
            
                <div class="fileinput fileinput-new" data-provides="fileinput">
                    <div id='img_destaque' class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;">
                    </div>
                    <div>
                        <span class="btn btn-default btn-file">
                            <span class="fileinput-new">Imagem</span>
                            <span class="fileinput-exists">Mudar</span>
                            <input type="file">
                        </span>
                        <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remover</a>
                        <a href="#" id="img_destaque_enviar" class="img_enviar btn btn-primary fileinput-exists" onclick="envia_img('img_destaque')">Enviar</a>
                        <a href="#" id="img_destaque_excluir" class="img_excluir btn btn-danger fileinput-exists disabled" >Excluir</a>
                    </div>
                </div>
            
            </div>
        
        </div>
        
        
        
        <?php echo $this->formRow($form->get('submit'));?>
    </form>
    
    <?php
    echo $this->form()->closeTag();
    ?>

    </div>
</div>
