<?php

$title = 'Anúncios';
$this->headTitle($title);

?>

<div xlass="row">
    
    <div xlass="row">
    <div class='col-xs-12' >
        
        <h1><?php echo $this->escapeHtml($title); ?></h1>
        
    </div>
    </div>
    
    <div xlass="row">
    <div class='col-xs-12' >
        
        <p>
            <a href="<?php echo $this->url('anuncio', array('action'=>'add'));?>">Adicionar novo anúncio</a>
        </p>
        
    </div>
    </div>
    
</div>



<?php foreach ($anuncios as $anuncio) : ?>

<div class="row">
               
   <div class="col-sm-3">
     <a href="#">
       <br>
       <img class="img-responsive" src="http://www.bootply.com/assets/example/ec_socks.jpg" data-alt="" data-title="">
     </a>
     <br>
     
    </div>
    <div class="col-sm-9">
      
      <h2><a class="url" href="#"> <?php echo $this->escapeHtml($anuncio->nmMat);?></a></h2>
      
      <ul class="list-group ticketView">
          <li class="list-group-item ticketView">
              <span class="label label-default">Marca</span>
              <label> <?php echo $this->escapeHtml($anuncio->marca);?></label>
          </li>
          <li class="list-group-item ticketView">
              <span class="label label-default">Preço</span>
              <label>R$ <?php echo $this->escapeHtml($anuncio->preco);?></label>
          </li>  
          <li class="list-group-item ticketView">
              <span class="label label-default">Sizes</span>
              <label> Mens's 5-10, 8-12</label>
          </li>
          <li class="list-group-item ticketView">
              <span class="label label-default">Stock #</span>
               N12325
          </li>
      </ul>
      
    </div><!--/col-->
</div><!--/row-->

<?php endforeach; ?>
            
        